
spring.activemq.broker-url=tcp://192.168.111.6:61616

### Change User Credentials!! 
spring.activemq.user=group6
spring.activemq.password=oi374bU0njDlI6m

# Client-Konfiguration
client.id=group6_ClientAppStub
# Region-Filter: leer = alle Regionen (optional z.B. basel, zürich, bern)
client.region=basel
# JobType-Filter: repair, maintenance (leer = alle Typen)
client.jobType=repair